//TIP To <b>Run</b> code, press <shortcut actionId="Run"/> or
// click the <icon src="AllIcons.Actions.Execute"/> icon in the gutter.
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.util.Scanner;
public class Main {

    public static void main(String[] args) {
        int n, sum = 0;
        Scanner sc = new Scanner(System.in);
        System.out.println("enter the number of elements in array: ");
        n = sc.nextInt();
        int arr[] =new int[n];
        System.out.println("Enter all the Elements: ");
        for(int i=0;i<arr.length; i++) {
            arr[i] = sc.nextInt();
            sum = sum+arr[i];
        }
        System.out.println("Sum of all the Elements = "+sum);
    }
}